# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Cellier
tagline:          '我们从未念及大爆炸前同挤奇点的友谊'
description:      '『he looks like a dog so』 『because he is a PM』'
url:              http://cellier.me

author:
  name:           'cellier'
  email:          cellier@mail.com

paginate:      10

# Custom vars
version:          0.0.3

# Comments

comments :
    provider : duoshuo
    duoshuo :
          short_name : cellier-me


